// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TB.EmailSubscriber.Persistence;

namespace TB.EmailSubscriber.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20181212171617_email_subscriber_v3")]
    partial class email_subscriber_v3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TB.EmailSubscriber.Models.SubscribtionTopic", b =>
                {
                    b.Property<int>("SubscriptionId");

                    b.Property<int>("TopicId");

                    b.HasKey("SubscriptionId", "TopicId");

                    b.HasIndex("TopicId");

                    b.ToTable("SubscribtionTopic");
                });

            modelBuilder.Entity("TB.EmailSubscriber.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<DateTime>("SubscribeDate");

                    b.Property<string>("UniqueToken");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("TB.EmailSubscriber.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("TB.EmailSubscriber.Models.SubscribtionTopic", b =>
                {
                    b.HasOne("TB.EmailSubscriber.Models.Subscription", "Subscription")
                        .WithMany("Topics")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TB.EmailSubscriber.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
